name: Deploy to Azure App Service

on:
  push:
    branches:
      - main   # or 'develop'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: hello-app-spring                  # exact name from Azure portal
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar                        # ensure your JAR is here